BEGIN;

/*
Title: Coreutils
Description: Application-specific whitelist for GNU coreutils
Publisher: WhiteBeam Security, Inc.
Version: 0.3.0-dev
*/

CREATE TEMPORARY TABLE IF NOT EXISTS global_const
AS SELECT (SELECT "/lib/" || (SELECT value FROM Setting WHERE param="SystemArchitecture") || "-linux-gnu/") AS LibraryPath;

INSERT OR IGNORE INTO Whitelist (parent, path, value, class)
WITH local_const AS (SELECT (SELECT id FROM WhitelistClass WHERE class="Filesystem/Path/Executable") AS Executable,
                            (SELECT id FROM WhitelistClass WHERE class="Filesystem/Path/Library") AS Library,
                            (SELECT id FROM WhitelistClass WHERE class="Hash/BLAKE3") AS BLAKE3)
SELECT * FROM (VALUES ("ANY", "ANY", "/bin/basename", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/cat", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/clear_console", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/cp", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/df", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/dircolors", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/dirname", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/env", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/free", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/grep", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/groups", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/id", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/lesspipe", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/locale-check", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/ls", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/mesg", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/ps", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/rm", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/uname", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/which", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/bin/w.procps", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/basename", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/cat", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/clear_console", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/cp", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/df", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/dircolors", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/dirname", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/env", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/free", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/grep", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/groups", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/id", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/lesspipe", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/locale-check", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/ls", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/mesg", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/ps", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/rm", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/uname", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/which", (SELECT Executable FROM local_const)),
                      ("ANY", "ANY", "/usr/bin/w.procps", (SELECT Executable FROM local_const)),
                      ("ANY", "/bin/clear_console", (SELECT LibraryPath FROM global_const) || "libtinfo.so.6", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/cp", (SELECT LibraryPath FROM global_const) || "libselinux.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/cp", (SELECT LibraryPath FROM global_const) || "libpcre2-8.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/cp", (SELECT LibraryPath FROM global_const) || "libacl.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/cp", (SELECT LibraryPath FROM global_const) || "libattr.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/free", (SELECT LibraryPath FROM global_const) || "libprocps.so.8", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/free", (SELECT LibraryPath FROM global_const) || "libsystemd.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/free", (SELECT LibraryPath FROM global_const) || "librt.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/free", (SELECT LibraryPath FROM global_const) || "liblzma.so.5", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/free", (SELECT LibraryPath FROM global_const) || "liblz4.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/free", (SELECT LibraryPath FROM global_const) || "libgcrypt.so.20", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/free", (SELECT LibraryPath FROM global_const) || "libgpg-error.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/grep", (SELECT LibraryPath FROM global_const) || "libpcre.so.3", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/id", (SELECT LibraryPath FROM global_const) || "libselinux.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/id", (SELECT LibraryPath FROM global_const) || "libpcre2-8.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/ls", (SELECT LibraryPath FROM global_const) || "libselinux.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/ls", (SELECT LibraryPath FROM global_const) || "libpcre2-8.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/ps", (SELECT LibraryPath FROM global_const) || "libprocps.so.8", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/ps", (SELECT LibraryPath FROM global_const) || "libsystemd.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/ps", (SELECT LibraryPath FROM global_const) || "librt.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/ps", (SELECT LibraryPath FROM global_const) || "liblzma.so.5", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/ps", (SELECT LibraryPath FROM global_const) || "liblz4.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/ps", (SELECT LibraryPath FROM global_const) || "libgcrypt.so.20", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/ps", (SELECT LibraryPath FROM global_const) || "libgpg-error.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/w.procps", (SELECT LibraryPath FROM global_const) || "libprocps.so.8", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/w.procps", (SELECT LibraryPath FROM global_const) || "libsystemd.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/w.procps", (SELECT LibraryPath FROM global_const) || "librt.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/w.procps", (SELECT LibraryPath FROM global_const) || "liblzma.so.5", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/w.procps", (SELECT LibraryPath FROM global_const) || "liblz4.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/w.procps", (SELECT LibraryPath FROM global_const) || "libgcrypt.so.20", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/w.procps", (SELECT LibraryPath FROM global_const) || "libgpg-error.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/clear_console", (SELECT LibraryPath FROM global_const) || "libtinfo.so.6", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/cp", (SELECT LibraryPath FROM global_const) || "libselinux.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/cp", (SELECT LibraryPath FROM global_const) || "libpcre2-8.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/cp", (SELECT LibraryPath FROM global_const) || "libacl.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/cp", (SELECT LibraryPath FROM global_const) || "libattr.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/free", (SELECT LibraryPath FROM global_const) || "libprocps.so.8", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/free", (SELECT LibraryPath FROM global_const) || "libsystemd.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/free", (SELECT LibraryPath FROM global_const) || "librt.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/free", (SELECT LibraryPath FROM global_const) || "liblzma.so.5", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/free", (SELECT LibraryPath FROM global_const) || "liblz4.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/free", (SELECT LibraryPath FROM global_const) || "libgcrypt.so.20", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/free", (SELECT LibraryPath FROM global_const) || "libgpg-error.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/grep", (SELECT LibraryPath FROM global_const) || "libpcre.so.3", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/id", (SELECT LibraryPath FROM global_const) || "libselinux.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/id", (SELECT LibraryPath FROM global_const) || "libpcre2-8.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/ls", (SELECT LibraryPath FROM global_const) || "libselinux.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/ls", (SELECT LibraryPath FROM global_const) || "libpcre2-8.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/ps", (SELECT LibraryPath FROM global_const) || "libprocps.so.8", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/ps", (SELECT LibraryPath FROM global_const) || "libsystemd.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/ps", (SELECT LibraryPath FROM global_const) || "librt.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/ps", (SELECT LibraryPath FROM global_const) || "liblzma.so.5", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/ps", (SELECT LibraryPath FROM global_const) || "liblz4.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/ps", (SELECT LibraryPath FROM global_const) || "libgcrypt.so.20", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/ps", (SELECT LibraryPath FROM global_const) || "libgpg-error.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/w.procps", (SELECT LibraryPath FROM global_const) || "libprocps.so.8", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/w.procps", (SELECT LibraryPath FROM global_const) || "libsystemd.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/w.procps", (SELECT LibraryPath FROM global_const) || "librt.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/w.procps", (SELECT LibraryPath FROM global_const) || "liblzma.so.5", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/w.procps", (SELECT LibraryPath FROM global_const) || "liblz4.so.1", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/w.procps", (SELECT LibraryPath FROM global_const) || "libgcrypt.so.20", (SELECT Library FROM local_const)),
                      ("ANY", "/usr/bin/w.procps", (SELECT LibraryPath FROM global_const) || "libgpg-error.so.0", (SELECT Library FROM local_const)),
                      ("ANY", "/bin/basename", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/cat", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/clear_console", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/cp", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/df", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/dircolors", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/dirname", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/env", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/free", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/grep", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/groups", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/id", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/lesspipe", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/locale-check", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/ls", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/mesg", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/ps", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/rm", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/uname", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/which", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/bin/w.procps", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libtinfo.so.6", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libselinux.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libpcre2-8.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libacl.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libattr.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libprocps.so.8", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libsystemd.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "librt.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "liblzma.so.5", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "liblz4.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libgcrypt.so.20", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libgpg-error.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libpcre.so.3", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libselinux.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libpcre2-8.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libselinux.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libpcre2-8.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libprocps.so.8", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libsystemd.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "librt.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "liblzma.so.5", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "liblz4.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libgcrypt.so.20", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libgpg-error.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libprocps.so.8", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libsystemd.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "librt.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "liblzma.so.5", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "liblz4.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libgcrypt.so.20", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libgpg-error.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libtinfo.so.6", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libselinux.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libpcre2-8.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libacl.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libattr.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libprocps.so.8", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libsystemd.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "librt.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "liblzma.so.5", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "liblz4.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libgcrypt.so.20", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libgpg-error.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libpcre.so.3", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libselinux.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libpcre2-8.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libselinux.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libpcre2-8.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libprocps.so.8", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libsystemd.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "librt.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "liblzma.so.5", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "liblz4.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libgcrypt.so.20", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libgpg-error.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libprocps.so.8", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libsystemd.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "librt.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "liblzma.so.5", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "liblz4.so.1", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libgcrypt.so.20", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", (SELECT LibraryPath FROM global_const) || "libgpg-error.so.0", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/basename", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/cat", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/clear_console", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/cp", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/df", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/dircolors", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/dirname", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/env", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/free", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/grep", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/groups", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/id", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/lesspipe", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/locale-check", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/ls", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/mesg", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/ps", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/rm", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/uname", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/which", "ANY", (SELECT BLAKE3 FROM local_const)),
                      ("ANY", "/usr/bin/w.procps", "ANY", (SELECT BLAKE3 FROM local_const)));

COMMIT;